# Generated by Django 5.0.6 on 2026-04-09 21:26

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetClassification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[A-Z0-9.]+$', 'Code must be uppercase alphanumeric characters or dots.')])),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='assets.assetclassification')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_classifications', to='tenants.tenant')),
            ],
            options={
                'db_table': 'assets_classification',
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_code', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[A-Z0-9\\-]{3,50}$', 'Asset code must match ^[A-Z0-9\\-]{3,50}$')])),
                ('name', models.CharField(max_length=200)),
                ('fingerprint', models.CharField(db_index=True, max_length=64)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='tenants.site')),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.assetclassification')),
            ],
            options={
                'db_table': 'assets_asset',
            },
        ),
        migrations.CreateModel(
            name='AssetVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('data_snapshot', models.JSONField(default=dict)),
                ('change_source', models.CharField(choices=[('MANUAL', 'Manual'), ('BULK_IMPORT', 'Bulk Import'), ('CORRECTION', 'Correction')], default='MANUAL', max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='assets.asset')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_versions_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assets_version',
                'ordering': ['-version_number'],
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_asset', to='assets.assetversion'),
        ),
        migrations.AddConstraint(
            model_name='assetclassification',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uq_classification_tenant_code'),
        ),
        migrations.AddConstraint(
            model_name='assetversion',
            constraint=models.UniqueConstraint(fields=('asset', 'version_number'), name='uq_asset_version_number'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(fields=('site', 'asset_code'), name='uq_asset_site_code'),
        ),
    ]
