# Generated by Django 5.0.6 on 2026-04-09 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='core_audit__entity__b88b7f_idx',
            old_name='core_audit_entity_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='core_audit__tenant__1fd580_idx',
            old_name='core_audit_tenant_ts_idx',
        ),
    ]
