# Generated by Django 5.0.6 on 2026-04-09 22:21

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_recipes', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipes', to='tenants.tenant')),
            ],
            options={
                'db_table': 'foodservice_recipe',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecipeVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('SUPERSEDED', 'Superseded'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('servings', models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_recipe_versions', to=settings.AUTH_USER_MODEL)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='foodservice.recipe')),
            ],
            options={
                'db_table': 'foodservice_recipe_version',
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='RecipeStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('instruction', models.TextField(max_length=2000)),
                ('recipe_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='foodservice.recipeversion')),
            ],
            options={
                'db_table': 'foodservice_recipe_step',
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ingredient_name', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('unit', models.CharField(choices=[('oz', 'Ounce'), ('lb', 'Pound'), ('cup', 'Cup'), ('tbsp', 'Tablespoon'), ('tsp', 'Teaspoon'), ('fl_oz', 'Fluid Ounce'), ('gal', 'Gallon'), ('qt', 'Quart'), ('pt', 'Pint'), ('each', 'Each'), ('pinch', 'Pinch')], max_length=10)),
                ('unit_cost', models.DecimalField(decimal_places=4, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('recipe_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='foodservice.recipeversion')),
            ],
            options={
                'db_table': 'foodservice_recipe_ingredient',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='recipeversion',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('recipe',), name='uq_recipe_one_active_version'),
        ),
        migrations.AddConstraint(
            model_name='recipeversion',
            constraint=models.UniqueConstraint(fields=('recipe', 'version_number'), name='uq_recipe_version_number'),
        ),
        migrations.AddConstraint(
            model_name='recipestep',
            constraint=models.UniqueConstraint(fields=('recipe_version', 'step_number'), name='uq_recipe_step_number'),
        ),
    ]
