# Generated by Django 5.0.6 on 2026-04-09 22:31

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodservice', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(choices=[('MILK', 'Milk'), ('EGGS', 'Eggs'), ('FISH', 'Fish'), ('SHELLFISH', 'Shellfish'), ('TREE_NUTS', 'Tree Nuts'), ('PEANUTS', 'Peanuts'), ('GLUTEN', 'Gluten'), ('SOY', 'Soy'), ('SESAME', 'Sesame'), ('SULFITES', 'Sulfites'), ('MUSTARD', 'Mustard'), ('CELERY', 'Celery'), ('LUPIN', 'Lupin'), ('MOLLUSKS', 'Mollusks'), ('NONE', 'None')], max_length=20, unique=True)),
            ],
            options={
                'db_table': 'foodservice_allergen',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='DishAddon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('addon_name', models.CharField(max_length=200)),
                ('additional_cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
            ],
            options={
                'db_table': 'foodservice_dish_addon',
                'ordering': ['addon_name'],
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_dishes', to=settings.AUTH_USER_MODEL)),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dishes', to='foodservice.recipe')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dishes', to='tenants.tenant')),
            ],
            options={
                'db_table': 'foodservice_dish',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DishAddonAllergen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('allergen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dish_addons', to='foodservice.allergen')),
                ('dish_addon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addon_allergens', to='foodservice.dishaddon')),
            ],
            options={
                'db_table': 'foodservice_dish_addon_allergen',
            },
        ),
        migrations.CreateModel(
            name='DishVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('SUPERSEDED', 'Superseded'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('calories', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('protein_g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('carbs_g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('fat_g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('per_serving_cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_dish_versions', to=settings.AUTH_USER_MODEL)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='foodservice.dish')),
            ],
            options={
                'db_table': 'foodservice_dish_version',
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='DishPortionSpec',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('portion_label', models.CharField(max_length=100)),
                ('serving_size_qty', models.DecimalField(decimal_places=4, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('serving_size_unit', models.CharField(max_length=50)),
                ('price_multiplier', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('dish_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portions', to='foodservice.dishversion')),
            ],
            options={
                'db_table': 'foodservice_dish_portion_spec',
                'ordering': ['portion_label'],
            },
        ),
        migrations.AddField(
            model_name='dishaddon',
            name='dish_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='foodservice.dishversion'),
        ),
        migrations.CreateModel(
            name='DishVersionAllergen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('allergen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dish_versions', to='foodservice.allergen')),
                ('dish_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_allergens', to='foodservice.dishversion')),
            ],
            options={
                'db_table': 'foodservice_dish_version_allergen',
            },
        ),
        migrations.AddConstraint(
            model_name='dishaddonallergen',
            constraint=models.UniqueConstraint(fields=('dish_addon', 'allergen'), name='uq_dish_addon_allergen'),
        ),
        migrations.AddConstraint(
            model_name='dishversion',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('dish',), name='uq_dish_one_active_version'),
        ),
        migrations.AddConstraint(
            model_name='dishversion',
            constraint=models.UniqueConstraint(fields=('dish', 'version_number'), name='uq_dish_version_number'),
        ),
        migrations.AddConstraint(
            model_name='dishversionallergen',
            constraint=models.UniqueConstraint(fields=('dish_version', 'allergen'), name='uq_dish_version_allergen'),
        ),
    ]
