# Generated by Django 5.0.6 on 2026-04-09 22:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodservice', '0002_allergen_dishaddon_dish_dishaddonallergen_and_more'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('sort_order', models.IntegerField(default=0)),
                ('availability_start', models.TimeField(blank=True, null=True)),
                ('availability_end', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'foodservice_menu_group',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_menus', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='tenants.tenant')),
            ],
            options={
                'db_table': 'foodservice_menu',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MenuGroupItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('dish_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='menu_items', to='foodservice.dishversion')),
                ('menu_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='foodservice.menugroup')),
            ],
            options={
                'db_table': 'foodservice_menu_group_item',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='MenuVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('UNPUBLISHED', 'Unpublished'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('description', models.CharField(blank=True, default='', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_menu_versions', to=settings.AUTH_USER_MODEL)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='foodservice.menu')),
            ],
            options={
                'db_table': 'foodservice_menu_version',
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='MenuSiteRelease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('released_at', models.DateTimeField(auto_now_add=True)),
                ('released_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_releases', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_releases', to='tenants.site')),
                ('menu_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_releases', to='foodservice.menuversion')),
            ],
            options={
                'db_table': 'foodservice_menu_site_release',
            },
        ),
        migrations.AddField(
            model_name='menugroup',
            name='menu_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='foodservice.menuversion'),
        ),
        migrations.AddConstraint(
            model_name='menugroupitem',
            constraint=models.UniqueConstraint(fields=('menu_group', 'dish_version'), name='uq_menu_group_dish_version'),
        ),
        migrations.AddConstraint(
            model_name='menusiterelease',
            constraint=models.UniqueConstraint(fields=('menu_version', 'site'), name='uq_menu_version_site'),
        ),
    ]
